module.exports = {
    EXPIRY_VERIFICATION_CODE_MINUTES: 5,
    EXPIRY_RESET_TOKEN_MINUTES: 5,
    EXPIRY_LOGIN_SHORT_TERM_TOKEN: '24h',
    EXPIRY_LOGIN_LONG_TERM_TOKEN: '1000d',
    EXPIRY_VERIFY_EMAIL: '5d',
    VERIFY_EMAIL_KEY: 'YourIDCode',
    MAIN_BACKEND_LINK_DOMAIN: `http://localhost`,
    SHORT_LINK_DOMAIN: 'http://localhost',
    ADMIN_TYPE: 'Powerful-Superuser',
}